import type { Question } from "../types";

export const Animals_Questions: Question[] = [
  // Animals - Easy
  {
    id: "ani_easy_1",
    statement: "Elephants are afraid of mice",
    answer: "faki",
    category: "animals",
    difficulty: "easy",
    explanation: "This is a myth! Elephants are not actually afraid of mice.",
  },
  {
    id: "ani_easy_2",
    statement: "Cats can see in complete darkness",
    answer: "faki",
    category: "animals",
    difficulty: "easy",
    explanation:
      "Cats need some light to see, they cannot see in complete darkness!",
  },
  {
    id: "ani_easy_3",
    statement: "Fish live in water",
    answer: "reyal",
    category: "animals",
    difficulty: "easy",
  },
  {
    id: "ani_easy_4",
    statement: "Birds have feathers",
    answer: "reyal",
    category: "animals",
    difficulty: "easy",
  },
  {
    id: "ani_easy_5",
    statement: "Snakes have legs",
    answer: "faki",
    category: "animals",
    difficulty: "easy",
    explanation: "Snakes do not have legs - they move by slithering!",
  },
  {
    id: "ani_easy_6",
    statement: "Dogs are mammals",
    answer: "reyal",
    category: "animals",
    difficulty: "easy",
  },
  {
    id: "ani_easy_7",
    statement: "Penguins live in the desert",
    answer: "faki",
    category: "animals",
    difficulty: "easy",
    explanation: "Penguins live in cold climates, especially Antarctica!",
  },
  {
    id: "ani_easy_8",
    statement: "Cows give milk",
    answer: "reyal",
    category: "animals",
    difficulty: "easy",
  },
  {
    id: "ani_easy_9",
    statement: "Lions are called the king of the jungle",
    answer: "reyal",
    category: "animals",
    difficulty: "easy",
  },
  {
    id: "ani_easy_10",
    statement: "Chickens can fly long distances",
    answer: "faki",
    category: "animals",
    difficulty: "easy",
    explanation: "Chickens can barely fly and only for very short distances!",
  },
  {
    id: "ani_easy_11",
    statement: "Bees make honey",
    answer: "reyal",
    category: "animals",
    difficulty: "easy",
  },
  {
    id: "ani_easy_12",
    statement: "Horses have four legs",
    answer: "reyal",
    category: "animals",
    difficulty: "easy",
  },
  {
    id: "ani_easy_13",
    statement: "Spiders are insects",
    answer: "faki",
    category: "animals",
    difficulty: "easy",
    explanation:
      "Spiders are arachnids, not insects! They have 8 legs instead of 6.",
  },
  {
    id: "ani_easy_14",
    statement: "Rabbits eat carrots",
    answer: "reyal",
    category: "animals",
    difficulty: "easy",
  },
  {
    id: "ani_easy_15",
    statement: "Sharks are fish",
    answer: "reyal",
    category: "animals",
    difficulty: "easy",
  },
  {
    id: "ani_easy_16",
    statement: "Owls sleep during the day",
    answer: "reyal",
    category: "animals",
    difficulty: "easy",
  },
  {
    id: "ani_easy_17",
    statement: "Kangaroos live in Australia",
    answer: "reyal",
    category: "animals",
    difficulty: "easy",
  },
  {
    id: "ani_easy_18",
    statement: "Goldfish have a 3-second memory",
    answer: "faki",
    category: "animals",
    difficulty: "easy",
    explanation:
      "This is a myth! Goldfish can remember things for months, not just 3 seconds.",
  },
  {
    id: "ani_easy_19",
    statement: "Dolphins are mammals",
    answer: "reyal",
    category: "animals",
    difficulty: "easy",
  },
  {
    id: "ani_easy_20",
    statement: "Bears hibernate in winter",
    answer: "reyal",
    category: "animals",
    difficulty: "easy",
  },
  // Animals - Medium
  {
    id: "ani_medium_1",
    statement: "Octopuses have three hearts",
    answer: "reyal",
    category: "animals",
    difficulty: "medium",
  },
  {
    id: "ani_medium_2",
    statement: "A group of lions is called a pack",
    answer: "faki",
    category: "animals",
    difficulty: "medium",
    explanation: "A group of lions is called a pride!",
  },
  {
    id: "ani_medium_3",
    statement: "Hummingbirds can fly backwards",
    answer: "reyal",
    category: "animals",
    difficulty: "medium",
  },
  {
    id: "ani_medium_4",
    statement: "Koalas are bears",
    answer: "faki",
    category: "animals",
    difficulty: "medium",
    explanation: "Koalas are marsupials, not bears!",
  },
  {
    id: "ani_medium_5",
    statement: "Butterflies taste with their feet",
    answer: "reyal",
    category: "animals",
    difficulty: "medium",
  },
  {
    id: "ani_medium_6",
    statement: "A rhinoceros horn is made of bone",
    answer: "faki",
    category: "animals",
    difficulty: "medium",
    explanation:
      "A rhinoceros horn is made of keratin, the same material as hair and nails!",
  },
  {
    id: "ani_medium_7",
    statement: "Flamingos are naturally pink",
    answer: "faki",
    category: "animals",
    difficulty: "medium",
    explanation:
      "Flamingos are born gray and turn pink from eating shrimp and algae!",
  },
  {
    id: "ani_medium_8",
    statement: "Whales are the largest animals on Earth",
    answer: "reyal",
    category: "animals",
    difficulty: "medium",
  },
  {
    id: "ani_medium_9",
    statement: "Chameleons change color to camouflage",
    answer: "faki",
    category: "animals",
    difficulty: "medium",
    explanation:
      "Chameleons change color primarily for communication and temperature regulation, not camouflage!",
  },
  {
    id: "ani_medium_10",
    statement: "Giraffes have the same number of neck vertebrae as humans",
    answer: "reyal",
    category: "animals",
    difficulty: "medium",
  },
  {
    id: "ani_medium_11",
    statement: "Polar bears have black skin",
    answer: "reyal",
    category: "animals",
    difficulty: "medium",
  },
  {
    id: "ani_medium_12",
    statement: "A group of crows is called a murder",
    answer: "reyal",
    category: "animals",
    difficulty: "medium",
  },
  {
    id: "ani_medium_13",
    statement: "Seahorses are mammals",
    answer: "faki",
    category: "animals",
    difficulty: "medium",
    explanation: "Seahorses are fish, not mammals!",
  },
  {
    id: "ani_medium_14",
    statement: "Crocodiles can live up to 100 years",
    answer: "reyal",
    category: "animals",
    difficulty: "medium",
  },
  {
    id: "ani_medium_15",
    statement: "Owls can rotate their heads 360 degrees",
    answer: "faki",
    category: "animals",
    difficulty: "medium",
    explanation:
      "Owls can rotate their heads about 270 degrees, not a full 360!",
  },
  {
    id: "ani_medium_16",
    statement: "Sloths only defecate once a week",
    answer: "reyal",
    category: "animals",
    difficulty: "medium",
  },
  {
    id: "ani_medium_17",
    statement: "Tigers have striped skin under their fur",
    answer: "reyal",
    category: "animals",
    difficulty: "medium",
  },
  {
    id: "ani_medium_18",
    statement: "Pandas are carnivores",
    answer: "faki",
    category: "animals",
    difficulty: "medium",
    explanation:
      "Pandas are technically classified as carnivores but are primarily herbivores, eating mostly bamboo!",
  },
  {
    id: "ani_medium_19",
    statement: "A shrimp's heart is in its head",
    answer: "reyal",
    category: "animals",
    difficulty: "medium",
  },
  {
    id: "ani_medium_20",
    statement: "Bats are blind",
    answer: "faki",
    category: "animals",
    difficulty: "medium",
    explanation:
      "This is a myth! Bats can see quite well, and some have excellent vision!",
  },
  // Animals - Hard
  {
    id: "ani_hard_1",
    statement: "The immortal jellyfish can reverse its aging process",
    answer: "reyal",
    category: "animals",
    difficulty: "hard",
  },
  {
    id: "ani_hard_2",
    statement: "A blue whale's heart weighs as much as a small elephant",
    answer: "reyal",
    category: "animals",
    difficulty: "hard",
  },
  {
    id: "ani_hard_3",
    statement:
      "Mantis shrimp have the most complex eyes in the animal kingdom with 16 types of color receptors",
    answer: "reyal",
    category: "animals",
    difficulty: "hard",
  },
  {
    id: "ani_hard_4",
    statement: "Tardigrades can survive in space for over 10 days",
    answer: "reyal",
    category: "animals",
    difficulty: "hard",
  },
  {
    id: "ani_hard_5",
    statement:
      "The pistol shrimp creates bubbles that reach temperatures hotter than the sun",
    answer: "reyal",
    category: "animals",
    difficulty: "hard",
  },
  {
    id: "ani_hard_6",
    statement: "Axolotls can regenerate their entire brain",
    answer: "faki",
    category: "animals",
    difficulty: "hard",
    explanation:
      "Axolotls can regenerate limbs, organs, and parts of their brain, but not their entire brain!",
  },
  {
    id: "ani_hard_7",
    statement:
      "The bombardier beetle can shoot boiling chemicals from its abdomen",
    answer: "reyal",
    category: "animals",
    difficulty: "hard",
  },
  {
    id: "ani_hard_8",
    statement: "Vampire bats have heat sensors to detect blood vessels",
    answer: "reyal",
    category: "animals",
    difficulty: "hard",
  },
  {
    id: "ani_hard_9",
    statement:
      "The wood frog can freeze solid in winter and thaw alive in spring",
    answer: "reyal",
    category: "animals",
    difficulty: "hard",
  },
  {
    id: "ani_hard_10",
    statement: "Cuttlefish have W-shaped pupils",
    answer: "reyal",
    category: "animals",
    difficulty: "hard",
  },
  {
    id: "ani_hard_11",
    statement:
      "The archerfish can shoot water up to 5 meters to knock insects into water",
    answer: "reyal",
    category: "animals",
    difficulty: "hard",
  },
  {
    id: "ani_hard_12",
    statement: "Naked mole rats are immune to cancer and pain",
    answer: "faki",
    category: "animals",
    difficulty: "hard",
    explanation:
      "Naked mole rats are highly resistant to cancer and insensitive to some types of pain, but not completely immune!",
  },
  {
    id: "ani_hard_13",
    statement: "The leafy sea dragon is related to seahorses",
    answer: "reyal",
    category: "animals",
    difficulty: "hard",
  },
  {
    id: "ani_hard_14",
    statement: "Electric eels can generate up to 600 volts of electricity",
    answer: "reyal",
    category: "animals",
    difficulty: "hard",
  },
  {
    id: "ani_hard_15",
    statement: "The blobfish only looks blob-like when brought to the surface",
    answer: "reyal",
    category: "animals",
    difficulty: "hard",
  },
  {
    id: "ani_hard_16",
    statement: "Platypuses sweat milk through their skin",
    answer: "reyal",
    category: "animals",
    difficulty: "hard",
  },
  {
    id: "ani_hard_17",
    statement: "The longest recorded flight of a chicken is 13 seconds",
    answer: "reyal",
    category: "animals",
    difficulty: "hard",
  },
  {
    id: "ani_hard_18",
    statement: "Honey badgers are immune to most snake venoms",
    answer: "reyal",
    category: "animals",
    difficulty: "hard",
  },
  {
    id: "ani_hard_19",
    statement: "The anglerfish male permanently fuses to the female's body",
    answer: "reyal",
    category: "animals",
    difficulty: "hard",
  },
  {
    id: "ani_hard_20",
    statement: "Sea otters hold hands while sleeping to avoid drifting apart",
    answer: "reyal",
    category: "animals",
    difficulty: "hard",
  },
  // Animals - Expert
  {
    id: "ani_expert_1",
    statement: "The Weddell seal can hold its breath for up to 82 minutes",
    answer: "reyal",
    category: "animals",
    difficulty: "expert",
  },
  {
    id: "ani_expert_2",
    statement:
      "Octopuses have blue blood due to hemocyanin instead of hemoglobin",
    answer: "reyal",
    category: "animals",
    difficulty: "expert",
  },
  {
    id: "ani_expert_3",
    statement: "The Arctic tern migrates roughly 44,000 miles annually",
    answer: "reyal",
    category: "animals",
    difficulty: "expert",
  },
  {
    id: "ani_expert_4",
    statement:
      "Bees perform the waggle dance to communicate distance and direction to food sources",
    answer: "reyal",
    category: "animals",
    difficulty: "expert",
  },
  {
    id: "ani_expert_5",
    statement:
      "The bar-tailed godwit can fly non-stop for 9 days during migration",
    answer: "reyal",
    category: "animals",
    difficulty: "expert",
  },
  {
    id: "ani_expert_6",
    statement: "Dolphins have signature whistles that function like names",
    answer: "reyal",
    category: "animals",
    difficulty: "expert",
  },
  {
    id: "ani_expert_7",
    statement: "The lungfish can survive out of water for up to 6 years",
    answer: "faki",
    category: "animals",
    difficulty: "expert",
    explanation:
      "The lungfish can survive out of water for up to 4 years by entering a dormant state called estivation!",
  },
  {
    id: "ani_expert_8",
    statement: "Lyrebirds can accurately mimic over 20 different bird species",
    answer: "reyal",
    category: "animals",
    difficulty: "expert",
  },
  {
    id: "ani_expert_9",
    statement: "The desert ant uses polarized light patterns to navigate",
    answer: "reyal",
    category: "animals",
    difficulty: "expert",
  },
  {
    id: "ani_expert_10",
    statement: "Sperm whales can dive to depths exceeding 3,000 meters",
    answer: "reyal",
    category: "animals",
    difficulty: "expert",
  },
  {
    id: "ani_expert_11",
    statement: "The African elephant pregnancy lasts 22 months",
    answer: "reyal",
    category: "animals",
    difficulty: "expert",
  },
  {
    id: "ani_expert_12",
    statement: "Peregrine falcons can reach diving speeds of 389 km/h",
    answer: "faki",
    category: "animals",
    difficulty: "expert",
    explanation:
      "Peregrine falcons can reach diving speeds of up to 320 km/h (200 mph)!",
  },
  {
    id: "ani_expert_13",
    statement:
      "The glass frog has transparent skin that reveals its internal organs",
    answer: "reyal",
    category: "animals",
    difficulty: "expert",
  },
  {
    id: "ani_expert_14",
    statement:
      "Clark's nutcracker can remember the locations of over 33,000 seed caches",
    answer: "reyal",
    category: "animals",
    difficulty: "expert",
  },
  {
    id: "ani_expert_15",
    statement:
      "The star-nosed mole can identify and consume prey in 230 milliseconds",
    answer: "reyal",
    category: "animals",
    difficulty: "expert",
  },
  {
    id: "ani_expert_16",
    statement:
      "Bowerbirds create elaborate structures to attract mates and decorate them with colorful objects",
    answer: "reyal",
    category: "animals",
    difficulty: "expert",
  },
  {
    id: "ani_expert_17",
    statement:
      "The wandering albatross has the largest wingspan of any living bird at up to 3.7 meters",
    answer: "reyal",
    category: "animals",
    difficulty: "expert",
  },
  {
    id: "ani_expert_18",
    statement:
      "Cephalopods can rapidly change both color and texture through chromatophores and papillae",
    answer: "reyal",
    category: "animals",
    difficulty: "expert",
  },
  {
    id: "ani_expert_19",
    statement:
      "The Greenland shark can live over 400 years and doesn't reach sexual maturity until 150 years old",
    answer: "reyal",
    category: "animals",
    difficulty: "expert",
  },
  {
    id: "ani_expert_20",
    statement:
      "Emperor penguins can dive to depths of 500 meters and hold their breath for 27 minutes",
    answer: "faki",
    category: "animals",
    difficulty: "expert",
    explanation:
      "Emperor penguins can dive to depths of over 500 meters but typically hold their breath for about 18-20 minutes, with maximum recorded times around 22 minutes!",
  },
];
