import type { Question } from "../types";

export const Entertainment_Questions: Question[] = [
  // Entertainment - Easy
  {
    id: "ent_easy_1",
    statement: "Mickey Mouse was created by Walt Disney",
    answer: "reyal",
    category: "entertainment",
    difficulty: "easy",
  },
  {
    id: "ent_easy_2",
    statement: "The movie Titanic was released in 1990",
    answer: "faki",
    category: "entertainment",
    difficulty: "easy",
    explanation: "Titanic was released in 1997, not 1990!",
  },
  {
    id: "ent_easy_3",
    statement: "Harry Potter’s pet owl is named Hedwig",
    answer: "reyal",
    category: "entertainment",
    difficulty: "easy",
  },
  {
    id: "ent_easy_4",
    statement: "The Simpsons is the longest-running animated TV series",
    answer: "reyal",
    category: "entertainment",
    difficulty: "easy",
  },
  {
    id: "ent_easy_5",
    statement: "Elsa is a character from the Disney movie Frozen",
    answer: "reyal",
    category: "entertainment",
    difficulty: "easy",
  },
  {
    id: "ent_easy_6",
    statement: "Batman lives in Gotham City",
    answer: "reyal",
    category: "entertainment",
    difficulty: "easy",
  },
  {
    id: "ent_easy_7",
    statement:
      "In the Marvel movies, Tony Stark is also known as Captain America",
    answer: "faki",
    category: "entertainment",
    difficulty: "easy",
    explanation: "Tony Stark is Iron Man, not Captain America.",
  },
  {
    id: "ent_easy_8",
    statement: "The TV show Friends takes place in New York City",
    answer: "reyal",
    category: "entertainment",
    difficulty: "easy",
  },
  {
    id: "ent_easy_9",
    statement: "The character Shrek is a dragon",
    answer: "faki",
    category: "entertainment",
    difficulty: "easy",
    explanation: "Shrek is an ogre. Donkey falls in love with the dragon.",
  },
  {
    id: "ent_easy_10",
    statement: "The movie Finding Nemo features a clownfish",
    answer: "reyal",
    category: "entertainment",
    difficulty: "easy",
  },
  {
    id: "ent_easy_11",
    statement: "Spider-Man’s real name is Peter Parker",
    answer: "reyal",
    category: "entertainment",
    difficulty: "easy",
  },
  {
    id: "ent_easy_12",
    statement: "The Minions are yellow characters from the movie Despicable Me",
    answer: "reyal",
    category: "entertainment",
    difficulty: "easy",
  },
  {
    id: "ent_easy_13",
    statement: "Woody and Buzz Lightyear are characters from Toy Story",
    answer: "reyal",
    category: "entertainment",
    difficulty: "easy",
  },
  {
    id: "ent_easy_14",
    statement: "The Frozen song 'Let It Go' was sung by Elsa",
    answer: "reyal",
    category: "entertainment",
    difficulty: "easy",
  },
  {
    id: "ent_easy_15",
    statement: "The Black Panther movie is part of the DC Universe",
    answer: "faki",
    category: "entertainment",
    difficulty: "easy",
    explanation: "Black Panther belongs to Marvel, not DC.",
  },
  {
    id: "ent_easy_16",
    statement: "Homer Simpson loves donuts",
    answer: "reyal",
    category: "entertainment",
    difficulty: "easy",
  },
  {
    id: "ent_easy_17",
    statement: "In Star Wars, Yoda is a Jedi Master",
    answer: "reyal",
    category: "entertainment",
    difficulty: "easy",
  },
  {
    id: "ent_easy_18",
    statement: "In Frozen, Anna is Elsa’s sister",
    answer: "reyal",
    category: "entertainment",
    difficulty: "easy",
  },
  {
    id: "ent_easy_19",
    statement: "The movie Avengers: Endgame was released before The Avengers",
    answer: "faki",
    category: "entertainment",
    difficulty: "easy",
    explanation: "The Avengers (2012) came before Endgame (2019).",
  },
  {
    id: "ent_easy_20",
    statement: "The character Pikachu is from Pokémon",
    answer: "reyal",
    category: "entertainment",
    difficulty: "easy",
  },

  // Entertainment - Medium
  {
    id: "ent_med_1",
    statement: "In The Lion King, Simba’s father is named Mufasa",
    answer: "reyal",
    category: "entertainment",
    difficulty: "medium",
  },
  {
    id: "ent_med_2",
    statement: "In Stranger Things, Eleven’s favorite food is ice cream",
    answer: "faki",
    category: "entertainment",
    difficulty: "medium",
    explanation: "Her favorite food is Eggo waffles, not ice cream.",
  },
  {
    id: "ent_med_3",
    statement: "The movie Inception was directed by Christopher Nolan",
    answer: "reyal",
    category: "entertainment",
    difficulty: "medium",
  },
  {
    id: "ent_med_4",
    statement: "The actor who plays Jack in Titanic is Brad Pitt",
    answer: "faki",
    category: "entertainment",
    difficulty: "medium",
    explanation: "Jack was played by Leonardo DiCaprio.",
  },
  {
    id: "ent_med_5",
    statement:
      "In Harry Potter, the house colors of Gryffindor are red and gold",
    answer: "reyal",
    category: "entertainment",
    difficulty: "medium",
  },
  {
    id: "ent_med_6",
    statement:
      "The TV show Breaking Bad follows a chemistry teacher who becomes a drug dealer",
    answer: "reyal",
    category: "entertainment",
    difficulty: "medium",
  },
  {
    id: "ent_med_7",
    statement:
      "The actress who played Katniss Everdeen in The Hunger Games is Emma Watson",
    answer: "faki",
    category: "entertainment",
    difficulty: "medium",
    explanation: "Katniss was played by Jennifer Lawrence.",
  },
  {
    id: "ent_med_8",
    statement: "The Marvel character Thor wields a weapon called Mjolnir",
    answer: "reyal",
    category: "entertainment",
    difficulty: "medium",
  },
  {
    id: "ent_med_9",
    statement: "The Matrix features a red pill and a blue pill",
    answer: "reyal",
    category: "entertainment",
    difficulty: "medium",
  },
  {
    id: "ent_med_10",
    statement:
      "The TV series Game of Thrones is based on books by George R. R. Tolkien",
    answer: "faki",
    category: "entertainment",
    difficulty: "medium",
    explanation: "The books were written by George R. R. Martin, not Tolkien.",
  },
  {
    id: "ent_med_11",
    statement: "In Frozen, Olaf is the name of the snowman",
    answer: "reyal",
    category: "entertainment",
    difficulty: "medium",
  },
  {
    id: "ent_med_12",
    statement: "In Toy Story, the cowboy doll’s name is Andy",
    answer: "faki",
    category: "entertainment",
    difficulty: "medium",
    explanation: "Andy is the boy. The cowboy doll’s name is Woody.",
  },
  {
    id: "ent_med_13",
    statement: "The Netflix show Squid Game originated in South Korea",
    answer: "reyal",
    category: "entertainment",
    difficulty: "medium",
  },
  {
    id: "ent_med_14",
    statement: "In The Avengers, the Hulk’s real name is Bruce Wayne",
    answer: "faki",
    category: "entertainment",
    difficulty: "medium",
    explanation: "Bruce Wayne is Batman. Hulk’s real name is Bruce Banner.",
  },
  {
    id: "ent_med_15",
    statement: "The song 'Circle of Life' is featured in The Lion King",
    answer: "reyal",
    category: "entertainment",
    difficulty: "medium",
  },
  {
    id: "ent_med_16",
    statement: "In The Office (US), Michael Scott is played by Steve Carell",
    answer: "reyal",
    category: "entertainment",
    difficulty: "medium",
  },
  {
    id: "ent_med_17",
    statement: "In Frozen, Elsa sings 'Do You Want to Build a Snowman?'",
    answer: "faki",
    category: "entertainment",
    difficulty: "medium",
    explanation: "That song is sung by Anna, not Elsa.",
  },
  {
    id: "ent_med_18",
    statement: "In Black Panther, the fictional nation is called Wakanda",
    answer: "reyal",
    category: "entertainment",
    difficulty: "medium",
  },
  {
    id: "ent_med_19",
    statement:
      "The show Friends features characters named Ross, Monica, and Joey",
    answer: "reyal",
    category: "entertainment",
    difficulty: "medium",
  },
  {
    id: "ent_med_20",
    statement: "In Star Wars, Darth Vader says 'Luke, I am your father'",
    answer: "faki",
    category: "entertainment",
    difficulty: "medium",
    explanation: "The actual line is 'No, I am your father.'",
  },
  // Entertainment - Hard
  {
    id: "ent_hard_1",
    statement: "The film Pulp Fiction was directed by Quentin Tarantino",
    answer: "reyal",
    category: "entertainment",
    difficulty: "hard",
  },
  {
    id: "ent_hard_2",
    statement: "The Beatles originally had five members before becoming four",
    answer: "reyal",
    category: "entertainment",
    difficulty: "hard",
    explanation:
      "Stuart Sutcliffe was an early member before the famous four lineup.",
  },
  {
    id: "ent_hard_3",
    statement:
      "In The Godfather, the famous line 'Leave the gun, take the cannoli' was improvised",
    answer: "reyal",
    category: "entertainment",
    difficulty: "hard",
  },
  {
    id: "ent_hard_4",
    statement:
      "The movie Avatar (2009) surpassed Titanic as the highest-grossing film at the time",
    answer: "reyal",
    category: "entertainment",
    difficulty: "hard",
  },
  {
    id: "ent_hard_5",
    statement:
      "The actor who played Gandalf in The Lord of the Rings was Patrick Stewart",
    answer: "faki",
    category: "entertainment",
    difficulty: "hard",
    explanation: "Gandalf was played by Ian McKellen, not Patrick Stewart.",
  },
  {
    id: "ent_hard_6",
    statement:
      "In Star Wars, Yoda was originally going to be played by a monkey in a mask",
    answer: "reyal",
    category: "entertainment",
    difficulty: "hard",
  },
  {
    id: "ent_hard_7",
    statement:
      "In The Dark Knight, Heath Ledger won an Oscar posthumously for his role as The Joker",
    answer: "reyal",
    category: "entertainment",
    difficulty: "hard",
  },
  {
    id: "ent_hard_8",
    statement: "The Shining was directed by Stanley Kubrick",
    answer: "reyal",
    category: "entertainment",
    difficulty: "hard",
  },
  {
    id: "ent_hard_9",
    statement: "In Friends, the famous coffee shop is called Central Café",
    answer: "faki",
    category: "entertainment",
    difficulty: "hard",
    explanation: "It’s called Central Perk, not Central Café.",
  },
  {
    id: "ent_hard_10",
    statement:
      "The soundtrack of Guardians of the Galaxy is called 'Awesome Mix Vol. 1'",
    answer: "reyal",
    category: "entertainment",
    difficulty: "hard",
  },
  {
    id: "ent_hard_11",
    statement: "Breaking Bad’s Walter White’s alter ego is called 'Mr. White'",
    answer: "faki",
    category: "entertainment",
    difficulty: "hard",
    explanation: "His alter ego is 'Heisenberg,' not Mr. White.",
  },
  {
    id: "ent_hard_12",
    statement: "The Oscar-winning movie Parasite was directed by Bong Joon-ho",
    answer: "reyal",
    category: "entertainment",
    difficulty: "hard",
  },
  {
    id: "ent_hard_13",
    statement: "In The Simpsons, the bartender’s name is Moe",
    answer: "reyal",
    category: "entertainment",
    difficulty: "hard",
  },
  {
    id: "ent_hard_14",
    statement: "The movie Joker (2019) won the Academy Award for Best Picture",
    answer: "faki",
    category: "entertainment",
    difficulty: "hard",
    explanation:
      "Joker won Best Actor (Joaquin Phoenix) and Best Score, but not Best Picture.",
  },
  {
    id: "ent_hard_15",
    statement: "In Stranger Things, the Upside Down was first opened by Dustin",
    answer: "faki",
    category: "entertainment",
    difficulty: "hard",
    explanation:
      "The Upside Down was opened due to Eleven’s powers, not Dustin.",
  },
  {
    id: "ent_hard_16",
    statement:
      "In the Marvel Cinematic Universe, Iron Man was the first film released",
    answer: "reyal",
    category: "entertainment",
    difficulty: "hard",
  },
  {
    id: "ent_hard_17",
    statement: "The Silence of the Lambs features the line 'Hello, Clarice'",
    answer: "faki",
    category: "entertainment",
    difficulty: "hard",
    explanation:
      "Hannibal Lecter never actually says 'Hello, Clarice' in the film.",
  },
  {
    id: "ent_hard_18",
    statement: "In The Office (US), Jim Halpert marries Pam Beesly",
    answer: "reyal",
    category: "entertainment",
    difficulty: "hard",
  },
  {
    id: "ent_hard_19",
    statement:
      "In Game of Thrones, the Stark family’s motto is 'Winter is Here'",
    answer: "faki",
    category: "entertainment",
    difficulty: "hard",
    explanation: "Their motto is 'Winter is Coming,' not 'Winter is Here.'",
  },
  {
    id: "ent_hard_20",
    statement: "The film Casablanca was released during World War II",
    answer: "reyal",
    category: "entertainment",
    difficulty: "hard",
    explanation: "It was released in 1942, during the war.",
  },
  // Entertainment - Expert
  {
    id: "ent_expert_1",
    statement:
      "Citizen Kane is often considered one of the greatest films ever made",
    answer: "reyal",
    category: "entertainment",
    difficulty: "expert",
  },
  {
    id: "ent_expert_2",
    statement: "The first Academy Awards ceremony was held in 1929",
    answer: "reyal",
    category: "entertainment",
    difficulty: "expert",
  },
  {
    id: "ent_expert_3",
    statement:
      "Stan Lee makes a cameo in every Marvel Cinematic Universe movie up until Avengers: Endgame",
    answer: "reyal",
    category: "entertainment",
    difficulty: "expert",
  },
  {
    id: "ent_expert_4",
    statement:
      "The term 'Bollywood' refers to the film industry in Kolkata, India",
    answer: "faki",
    category: "entertainment",
    difficulty: "expert",
    explanation:
      "Bollywood refers to Hindi cinema based in Mumbai, not Kolkata.",
  },
  {
    id: "ent_expert_5",
    statement:
      "The Godfather Part II was the first sequel to win the Academy Award for Best Picture",
    answer: "reyal",
    category: "entertainment",
    difficulty: "expert",
  },
  {
    id: "ent_expert_6",
    statement:
      "In the film Inception, the spinning top falls at the end of the movie",
    answer: "faki",
    category: "entertainment",
    difficulty: "expert",
    explanation:
      "The ending is deliberately ambiguous — the top wobbles, but we never see it fall.",
  },
  {
    id: "ent_expert_7",
    statement: "Alfred Hitchcock never won an Academy Award for Best Director",
    answer: "reyal",
    category: "entertainment",
    difficulty: "expert",
  },
  {
    id: "ent_expert_8",
    statement: "The band Queen’s song 'Bohemian Rhapsody' was released in 1985",
    answer: "faki",
    category: "entertainment",
    difficulty: "expert",
    explanation: "It was released in 1975, not 1985.",
  },
  {
    id: "ent_expert_9",
    statement:
      "In Schindler’s List, the only color shown in the otherwise black-and-white film is a girl’s red coat",
    answer: "reyal",
    category: "entertainment",
    difficulty: "expert",
  },
  {
    id: "ent_expert_10",
    statement:
      "The anime Spirited Away won the Academy Award for Best Animated Feature",
    answer: "reyal",
    category: "entertainment",
    difficulty: "expert",
  },
  {
    id: "ent_expert_11",
    statement:
      "The longest-running scripted TV show in history is The Simpsons",
    answer: "reyal",
    category: "entertainment",
    difficulty: "expert",
  },
  {
    id: "ent_expert_12",
    statement: "Francis Ford Coppola directed Apocalypse Now",
    answer: "reyal",
    category: "entertainment",
    difficulty: "expert",
  },
  {
    id: "ent_expert_13",
    statement: "The song 'Smells Like Teen Spirit' was released by Pearl Jam",
    answer: "faki",
    category: "entertainment",
    difficulty: "expert",
    explanation: "It was released by Nirvana, not Pearl Jam.",
  },
  {
    id: "ent_expert_14",
    statement: "The actor who voiced Darth Vader was James Earl Jones",
    answer: "reyal",
    category: "entertainment",
    difficulty: "expert",
  },
  {
    id: "ent_expert_15",
    statement:
      "The Oscars were originally called the 'Academy Awards of Motion Picture Arts and Sciences'",
    answer: "reyal",
    category: "entertainment",
    difficulty: "expert",
  },
  {
    id: "ent_expert_16",
    statement:
      "In the film Fight Club, the first rule is 'You must talk about Fight Club'",
    answer: "faki",
    category: "entertainment",
    difficulty: "expert",
    explanation: "The first rule is 'You do not talk about Fight Club.'",
  },
  {
    id: "ent_expert_17",
    statement: "The band ABBA is from Sweden",
    answer: "reyal",
    category: "entertainment",
    difficulty: "expert",
  },
  {
    id: "ent_expert_18",
    statement:
      "The video game The Legend of Zelda: Ocarina of Time was released for the Nintendo 64",
    answer: "reyal",
    category: "entertainment",
    difficulty: "expert",
  },
  {
    id: "ent_expert_19",
    statement: "Orson Welles directed and starred in Citizen Kane",
    answer: "reyal",
    category: "entertainment",
    difficulty: "expert",
  },
  {
    id: "ent_expert_20",
    statement:
      "In the original Blade Runner, the replicant Roy Batty says the line 'Tears in rain'",
    answer: "reyal",
    category: "entertainment",
    difficulty: "expert",
    explanation:
      "The full line is part of his iconic 'Tears in rain' monologue.",
  },
];