import type { Question } from "../types";

export const History_Questions: Question[] = [
  // History - Easy
  {
    id: "hist_easy_1",
    statement: "World War II ended in 1945",
    answer: "reyal",
    category: "history",
    difficulty: "easy",
  },
  {
    id: "hist_easy_2",
    statement: "The Great Wall of China was built in one year",
    answer: "faki",
    category: "history",
    difficulty: "easy",
    explanation:
      "The Great Wall was built over many centuries, not in just one year!",
  },
  {
    id: "hist_easy_3",
    statement: "The first President of the United States was George Washington",
    answer: "reyal",
    category: "history",
    difficulty: "easy",
  },
  {
    id: "hist_easy_4",
    statement:
      "The Roman Empire was ruled by Julius Caesar as its first emperor",
    answer: "faki",
    category: "history",
    difficulty: "easy",
    explanation:
      "Julius Caesar was a dictator, but the first emperor was Augustus.",
  },
  {
    id: "hist_easy_5",
    statement: "The pyramids of Egypt are more than 4,000 years old",
    answer: "reyal",
    category: "history",
    difficulty: "easy",
  },
  {
    id: "hist_easy_6",
    statement: "Christopher Columbus reached Asia in 1492",
    answer: "faki",
    category: "history",
    difficulty: "easy",
    explanation: "He reached the Americas, not Asia.",
  },
  {
    id: "hist_easy_7",
    statement: "World War I was fought between 1914 and 1918",
    answer: "reyal",
    category: "history",
    difficulty: "easy",
  },
  {
    id: "hist_easy_8",
    statement: "The Great Fire of London happened in 1666",
    answer: "reyal",
    category: "history",
    difficulty: "easy",
  },
  {
    id: "hist_easy_9",
    statement:
      "The Cold War was a direct military conflict between the USA and USSR",
    answer: "faki",
    category: "history",
    difficulty: "easy",
    explanation:
      "It was a political and ideological conflict, not a direct war.",
  },
  {
    id: "hist_easy_10",
    statement: "The Berlin Wall divided East and West Berlin",
    answer: "reyal",
    category: "history",
    difficulty: "easy",
  },
  {
    id: "hist_easy_11",
    statement: "Ancient Rome was built on seven hills",
    answer: "reyal",
    category: "history",
    difficulty: "easy",
  },
  {
    id: "hist_easy_12",
    statement: "The American Civil War ended in 1776",
    answer: "faki",
    category: "history",
    difficulty: "easy",
    explanation:
      "1776 was the year of American independence. The Civil War ended in 1865.",
  },
  {
    id: "hist_easy_13",
    statement: "The Wright brothers invented the airplane",
    answer: "reyal",
    category: "history",
    difficulty: "easy",
  },
  {
    id: "hist_easy_14",
    statement: "The Titanic sank on its first voyage",
    answer: "reyal",
    category: "history",
    difficulty: "easy",
  },
  {
    id: "hist_easy_15",
    statement: "The United Nations was formed after World War I",
    answer: "faki",
    category: "history",
    difficulty: "easy",
    explanation: "It was formed in 1945 after World War II.",
  },
  {
    id: "hist_easy_16",
    statement: "The French Revolution began in 1789",
    answer: "reyal",
    category: "history",
    difficulty: "easy",
  },
  {
    id: "hist_easy_17",
    statement: "Marco Polo was an explorer from Spain",
    answer: "faki",
    category: "history",
    difficulty: "easy",
    explanation: "He was from Venice, Italy.",
  },
  {
    id: "hist_easy_18",
    statement: "The Great Depression began in 1929",
    answer: "reyal",
    category: "history",
    difficulty: "easy",
  },
  {
    id: "hist_easy_19",
    statement: "The Berlin Wall fell in 1989",
    answer: "reyal",
    category: "history",
    difficulty: "easy",
  },
  {
    id: "hist_easy_20",
    statement: "Leonardo da Vinci painted the Mona Lisa",
    answer: "reyal",
    category: "history",
    difficulty: "easy",
  },
  {
    id: "hist_easy_21",
    statement: "The Vikings originated from North America",
    answer: "faki",
    category: "history",
    difficulty: "easy",
    explanation: "They came from Scandinavia (Norway, Denmark, Sweden).",
  },
  {
    id: "hist_easy_22",
    statement: "The Declaration of Independence was signed in 1776",
    answer: "reyal",
    category: "history",
    difficulty: "easy",
  },

  // History - Medium
  {
    id: "hist_med_1",
    statement: "The Magna Carta was signed in 1215",
    answer: "reyal",
    category: "history",
    difficulty: "medium",
  },
  {
    id: "hist_med_2",
    statement: "Cleopatra was of Egyptian descent",
    answer: "faki",
    category: "history",
    difficulty: "medium",
    explanation: "She was Macedonian Greek, though she ruled Egypt.",
  },
  {
    id: "hist_med_3",
    statement: "The Renaissance began in Italy",
    answer: "reyal",
    category: "history",
    difficulty: "medium",
  },
  {
    id: "hist_med_4",
    statement: "The Black Death occurred in the 14th century",
    answer: "reyal",
    category: "history",
    difficulty: "medium",
  },
  {
    id: "hist_med_5",
    statement: "Genghis Khan founded the Ottoman Empire",
    answer: "faki",
    category: "history",
    difficulty: "medium",
    explanation:
      "He founded the Mongol Empire. The Ottoman Empire was founded by Osman I.",
  },
  {
    id: "hist_med_6",
    statement: "The U.S. Constitution was signed in 1787",
    answer: "reyal",
    category: "history",
    difficulty: "medium",
  },
  {
    id: "hist_med_7",
    statement: "The Hundred Years' War lasted exactly 100 years",
    answer: "faki",
    category: "history",
    difficulty: "medium",
    explanation: "It lasted 116 years, from 1337 to 1453.",
  },
  {
    id: "hist_med_8",
    statement:
      "The Berlin Conference of 1884–85 regulated European colonization of Africa",
    answer: "reyal",
    category: "history",
    difficulty: "medium",
  },
  {
    id: "hist_med_9",
    statement: "Joan of Arc was executed by burning at the stake",
    answer: "reyal",
    category: "history",
    difficulty: "medium",
  },
  {
    id: "hist_med_10",
    statement:
      "Mao Zedong was the first leader of the People's Republic of China",
    answer: "reyal",
    category: "history",
    difficulty: "medium",
  },
  {
    id: "hist_med_11",
    statement: "The Russian Revolution of 1917 overthrew the Ottoman Empire",
    answer: "faki",
    category: "history",
    difficulty: "medium",
    explanation: "It overthrew the Russian monarchy, not the Ottomans.",
  },
  {
    id: "hist_med_12",
    statement:
      "The Great Wall of China was primarily built to defend against Mongol invasions",
    answer: "reyal",
    category: "history",
    difficulty: "medium",
  },
  {
    id: "hist_med_13",
    statement: "The Mayan civilization was located in present-day Egypt",
    answer: "faki",
    category: "history",
    difficulty: "medium",
    explanation:
      "It was located in Central America (Mexico, Guatemala, Honduras).",
  },
  {
    id: "hist_med_14",
    statement: "The Industrial Revolution began in Britain",
    answer: "reyal",
    category: "history",
    difficulty: "medium",
  },
  {
    id: "hist_med_15",
    statement: "Nelson Mandela was imprisoned for 27 years",
    answer: "reyal",
    category: "history",
    difficulty: "medium",
  },
  {
    id: "hist_med_16",
    statement: "The Cuban Missile Crisis occurred in 1962",
    answer: "reyal",
    category: "history",
    difficulty: "medium",
  },
  {
    id: "hist_med_17",
    statement:
      "The American Revolutionary War was fought between Britain and France",
    answer: "faki",
    category: "history",
    difficulty: "medium",
    explanation: "It was fought between Britain and the American colonies.",
  },
  {
    id: "hist_med_18",
    statement: "Alexander the Great was tutored by Aristotle",
    answer: "reyal",
    category: "history",
    difficulty: "medium",
  },
  {
    id: "hist_med_19",
    statement: "The Bolsheviks were a faction in the Russian Revolution",
    answer: "reyal",
    category: "history",
    difficulty: "medium",
  },
  {
    id: "hist_med_20",
    statement: "The Spanish Armada defeated England in 1588",
    answer: "faki",
    category: "history",
    difficulty: "medium",
    explanation:
      "The Armada was defeated by England, not the other way around.",
  },

  // History - Hard
  {
    id: "hist_hard_1",
    statement: "Napoleon was actually of average height for his time",
    answer: "reyal",
    category: "history",
    difficulty: "hard",
    explanation:
      "Napoleon was about 5'7\", which was average or even slightly above average for men of his era!",
  },
  {
    id: "hist_hard_2",
    statement: "The Treaty of Versailles officially ended World War I",
    answer: "reyal",
    category: "history",
    difficulty: "hard",
  },
  {
    id: "hist_hard_3",
    statement: "The Byzantine Empire fell in 1453",
    answer: "reyal",
    category: "history",
    difficulty: "hard",
  },
  {
    id: "hist_hard_4",
    statement: "The Battle of Hastings occurred in 1066",
    answer: "reyal",
    category: "history",
    difficulty: "hard",
  },
  {
    id: "hist_hard_5",
    statement: "The Inca Empire was conquered by Hernán Cortés",
    answer: "faki",
    category: "history",
    difficulty: "hard",
    explanation:
      "Cortés conquered the Aztec Empire. Francisco Pizarro conquered the Incas.",
  },
  {
    id: "hist_hard_6",
    statement: "Charlemagne was crowned Holy Roman Emperor in the year 800",
    answer: "reyal",
    category: "history",
    difficulty: "hard",
  },
  {
    id: "hist_hard_7",
    statement: "The Thirty Years' War was primarily fought in France",
    answer: "faki",
    category: "history",
    difficulty: "hard",
    explanation:
      "It was fought mostly in Central Europe, especially the Holy Roman Empire.",
  },
  {
    id: "hist_hard_8",
    statement: "The Meiji Restoration began in Japan in 1868",
    answer: "reyal",
    category: "history",
    difficulty: "hard",
  },
  {
    id: "hist_hard_9",
    statement: "The Opium Wars were fought between Britain and China",
    answer: "reyal",
    category: "history",
    difficulty: "hard",
  },
  {
    id: "hist_hard_10",
    statement: "The Bolshevik Revolution took place in 1917",
    answer: "reyal",
    category: "history",
    difficulty: "hard",
  },
  {
    id: "hist_hard_11",
    statement: "The Spanish Civil War ended in 1939",
    answer: "reyal",
    category: "history",
    difficulty: "hard",
  },
  {
    id: "hist_hard_12",
    statement: "The Berlin Airlift occurred in the 1970s",
    answer: "faki",
    category: "history",
    difficulty: "hard",
    explanation: "It happened in 1948–1949 during the early Cold War.",
  },
  {
    id: "hist_hard_13",
    statement:
      "The Taiping Rebellion was one of the deadliest conflicts in history",
    answer: "reyal",
    category: "history",
    difficulty: "hard",
  },
  {
    id: "hist_hard_14",
    statement:
      "The Marshall Plan was a Soviet program to rebuild Eastern Europe",
    answer: "faki",
    category: "history",
    difficulty: "hard",
    explanation: "The Marshall Plan was a U.S. program to aid Western Europe.",
  },
  {
    id: "hist_hard_15",
    statement:
      "The assassination of Archduke Franz Ferdinand sparked World War I",
    answer: "reyal",
    category: "history",
    difficulty: "hard",
  },
  {
    id: "hist_hard_16",
    statement: "The Partition of India and Pakistan occurred in 1947",
    answer: "reyal",
    category: "history",
    difficulty: "hard",
  },
  {
    id: "hist_hard_17",
    statement: "The Ming dynasty directly succeeded the Qing dynasty",
    answer: "faki",
    category: "history",
    difficulty: "hard",
    explanation:
      "The Ming came before the Qing. The Qing dynasty followed the Ming.",
  },
  {
    id: "hist_hard_18",
    statement: "The Congress of Vienna took place after the Napoleonic Wars",
    answer: "reyal",
    category: "history",
    difficulty: "hard",
  },
  {
    id: "hist_hard_19",
    statement: "The Khmer Rouge regime in Cambodia was led by Pol Pot",
    answer: "reyal",
    category: "history",
    difficulty: "hard",
  },
  {
    id: "hist_hard_20",
    statement: "The Suez Crisis occurred in 1956",
    answer: "reyal",
    category: "history",
    difficulty: "hard",
  },

  // History - Expert
  {
    id: "hist_expert_1",
    statement:
      "The Treaty of Tordesillas in 1494 divided the New World between Spain and Portugal",
    answer: "reyal",
    category: "history",
    difficulty: "expert",
  },
  {
    id: "hist_expert_2",
    statement: "The Peace of Westphalia ended the Thirty Years’ War in 1648",
    answer: "reyal",
    category: "history",
    difficulty: "expert",
  },
  {
    id: "hist_expert_3",
    statement: "The Council of Trent was part of the Protestant Reformation",
    answer: "faki",
    category: "history",
    difficulty: "expert",
    explanation:
      "It was part of the Catholic Counter-Reformation, not Protestant.",
  },
  {
    id: "hist_expert_4",
    statement:
      "The Crimean War involved Britain, France, the Ottoman Empire, and Russia",
    answer: "reyal",
    category: "history",
    difficulty: "expert",
  },
  {
    id: "hist_expert_5",
    statement:
      "The Treaty of Brest-Litovsk ended Russia’s involvement in World War I",
    answer: "reyal",
    category: "history",
    difficulty: "expert",
  },
  {
    id: "hist_expert_6",
    statement: "The Boxer Rebellion occurred in India in the late 19th century",
    answer: "faki",
    category: "history",
    difficulty: "expert",
    explanation: "It occurred in China (1899–1901), not India.",
  },
  {
    id: "hist_expert_7",
    statement:
      "The Edict of Nantes granted religious freedom to French Protestants",
    answer: "reyal",
    category: "history",
    difficulty: "expert",
  },
  {
    id: "hist_expert_8",
    statement:
      "The Balfour Declaration of 1917 supported the establishment of a Jewish homeland in Palestine",
    answer: "reyal",
    category: "history",
    difficulty: "expert",
  },
  {
    id: "hist_expert_9",
    statement:
      "The Zulu Kingdom was founded by King Shaka in the early 19th century",
    answer: "reyal",
    category: "history",
    difficulty: "expert",
  },
  {
    id: "hist_expert_10",
    statement:
      "The Marshall Plan was formally known as the European Recovery Program",
    answer: "reyal",
    category: "history",
    difficulty: "expert",
  },
  {
    id: "hist_expert_11",
    statement: "The Treaty of Utrecht ended the Napoleonic Wars",
    answer: "faki",
    category: "history",
    difficulty: "expert",
    explanation:
      "It ended the War of the Spanish Succession in 1713, not the Napoleonic Wars.",
  },
  {
    id: "hist_expert_12",
    statement: "The Tokugawa shogunate ruled Japan from 1603 to 1868",
    answer: "reyal",
    category: "history",
    difficulty: "expert",
  },
  {
    id: "hist_expert_13",
    statement:
      "The Congress of Berlin in 1884–85 regulated European colonization of Africa",
    answer: "reyal",
    category: "history",
    difficulty: "expert",
  },
  {
    id: "hist_expert_14",
    statement: "The Peloponnesian War was fought between Athens and Carthage",
    answer: "faki",
    category: "history",
    difficulty: "expert",
    explanation: "It was fought between Athens and Sparta (431–404 BCE).",
  },
  {
    id: "hist_expert_15",
    statement:
      "The Warsaw Pact was a military alliance formed in 1955 among Soviet-aligned nations",
    answer: "reyal",
    category: "history",
    difficulty: "expert",
  },
  {
    id: "hist_expert_16",
    statement:
      "The Byzantine emperor Justinian I commissioned the Hagia Sophia",
    answer: "reyal",
    category: "history",
    difficulty: "expert",
  },
  {
    id: "hist_expert_17",
    statement: "The Punic Wars were fought between Rome and Greece",
    answer: "faki",
    category: "history",
    difficulty: "expert",
    explanation: "They were fought between Rome and Carthage.",
  },
  {
    id: "hist_expert_18",
    statement: "The Taiping Rebellion was led by Hong Xiuquan",
    answer: "reyal",
    category: "history",
    difficulty: "expert",
  },
  {
    id: "hist_expert_19",
    statement:
      "The Battle of Lepanto in 1571 was a naval battle where the Ottoman fleet was defeated",
    answer: "reyal",
    category: "history",
    difficulty: "expert",
  },
  {
    id: "hist_expert_20",
    statement: "The Edict of Worms declared Martin Luther an outlaw",
    answer: "reyal",
    category: "history",
    difficulty: "expert",
  },
];
