import type { Question } from "../types";

export const Sports_Questions: Question[] = [
  // Sports - Easy
  {
    id: "spo_easy_1",
    statement: "A soccer ball is round",
    answer: "reyal",
    category: "sports",
    difficulty: "easy",
  },
  {
    id: "spo_easy_2",
    statement: "Basketball was invented in China",
    answer: "faki",
    category: "sports",
    difficulty: "easy",
    explanation:
      "Basketball was invented in the United States by James Naismith in 1891!",
  },
  {
    id: "spo_easy_3",
    statement: "Tennis is played with a racket",
    answer: "reyal",
    category: "sports",
    difficulty: "easy",
  },
  {
    id: "spo_easy_4",
    statement: "A football field has 100 yards between end zones",
    answer: "reyal",
    category: "sports",
    difficulty: "easy",
  },
  {
    id: "spo_easy_5",
    statement: "Baseball is played with 11 players on each team",
    answer: "faki",
    category: "sports",
    difficulty: "easy",
    explanation: "Baseball is played with 9 players on each team!",
  },
  {
    id: "spo_easy_6",
    statement: "Swimming is done in water",
    answer: "reyal",
    category: "sports",
    difficulty: "easy",
  },
  {
    id: "spo_easy_7",
    statement: "Hockey players use sticks",
    answer: "reyal",
    category: "sports",
    difficulty: "easy",
  },
  {
    id: "spo_easy_8",
    statement: "Golf is played with a small white ball",
    answer: "reyal",
    category: "sports",
    difficulty: "easy",
  },
  {
    id: "spo_easy_9",
    statement: "Boxing matches are fought in a circle",
    answer: "faki",
    category: "sports",
    difficulty: "easy",
    explanation: "Boxing matches are fought in a square ring!",
  },
  {
    id: "spo_easy_10",
    statement: "Volleyball is played with a net",
    answer: "reyal",
    category: "sports",
    difficulty: "easy",
  },
  {
    id: "spo_easy_11",
    statement: "Track and field events include running",
    answer: "reyal",
    category: "sports",
    difficulty: "easy",
  },
  {
    id: "spo_easy_12",
    statement: "Ice skating is done on grass",
    answer: "faki",
    category: "sports",
    difficulty: "easy",
    explanation: "Ice skating is done on ice!",
  },
  {
    id: "spo_easy_13",
    statement: "Bowling pins are white",
    answer: "reyal",
    category: "sports",
    difficulty: "easy",
  },
  {
    id: "spo_easy_14",
    statement: "Cyclists ride bicycles",
    answer: "reyal",
    category: "sports",
    difficulty: "easy",
  },
  {
    id: "spo_easy_15",
    statement: "Wrestling involves two people",
    answer: "reyal",
    category: "sports",
    difficulty: "easy",
  },
  {
    id: "spo_easy_16",
    statement: "Gymnastics requires flexibility",
    answer: "reyal",
    category: "sports",
    difficulty: "easy",
  },
  {
    id: "spo_easy_17",
    statement: "Badminton is played with a shuttlecock",
    answer: "reyal",
    category: "sports",
    difficulty: "easy",
  },
  {
    id: "spo_easy_18",
    statement: "Surfing is done on snow",
    answer: "faki",
    category: "sports",
    difficulty: "easy",
    explanation: "Surfing is done on water waves!",
  },
  {
    id: "spo_easy_19",
    statement: "Table tennis uses paddles",
    answer: "reyal",
    category: "sports",
    difficulty: "easy",
  },
  {
    id: "spo_easy_20",
    statement: "Running is a form of exercise",
    answer: "reyal",
    category: "sports",
    difficulty: "easy",
  },

  // Sports - Medium
  {
    id: "spo_medium_1",
    statement: "The FIFA World Cup is held every 4 years",
    answer: "reyal",
    category: "sports",
    difficulty: "medium",
  },
  {
    id: "spo_medium_2",
    statement: "A perfect game in bowling is 200 points",
    answer: "faki",
    category: "sports",
    difficulty: "medium",
    explanation: "A perfect game in bowling is 300 points!",
  },
  {
    id: "spo_medium_3",
    statement: "Golf courses typically have 18 holes",
    answer: "reyal",
    category: "sports",
    difficulty: "medium",
  },
  {
    id: "spo_medium_4",
    statement: "The marathon distance is 26.2 miles",
    answer: "reyal",
    category: "sports",
    difficulty: "medium",
  },
  {
    id: "spo_medium_5",
    statement: "A volleyball team has 7 players on the court",
    answer: "faki",
    category: "sports",
    difficulty: "medium",
    explanation: "A volleyball team has 6 players on the court!",
  },
  {
    id: "spo_medium_6",
    statement: "The Olympics are held every 2 years",
    answer: "faki",
    category: "sports",
    difficulty: "medium",
    explanation:
      "The Summer and Winter Olympics each occur every 4 years, alternating every 2 years!",
  },
  {
    id: "spo_medium_7",
    statement: "A basketball game has four quarters",
    answer: "reyal",
    category: "sports",
    difficulty: "medium",
  },
  {
    id: "spo_medium_8",
    statement: "Tennis scoring goes 15, 30, 40, game",
    answer: "reyal",
    category: "sports",
    difficulty: "medium",
  },
  {
    id: "spo_medium_9",
    statement: "American football teams have 12 players on the field",
    answer: "faki",
    category: "sports",
    difficulty: "medium",
    explanation: "American football teams have 11 players on the field!",
  },
  {
    id: "spo_medium_10",
    statement: "A soccer match lasts 90 minutes",
    answer: "reyal",
    category: "sports",
    difficulty: "medium",
  },
  {
    id: "spo_medium_11",
    statement: "The Super Bowl is played in February",
    answer: "reyal",
    category: "sports",
    difficulty: "medium",
  },
  {
    id: "spo_medium_12",
    statement: "Ice hockey periods last 15 minutes each",
    answer: "faki",
    category: "sports",
    difficulty: "medium",
    explanation: "Ice hockey periods last 20 minutes each!",
  },
  {
    id: "spo_medium_13",
    statement: "Wimbledon is played on grass courts",
    answer: "reyal",
    category: "sports",
    difficulty: "medium",
  },
  {
    id: "spo_medium_14",
    statement: "A regulation basketball hoop is 10 feet high",
    answer: "reyal",
    category: "sports",
    difficulty: "medium",
  },
  {
    id: "spo_medium_15",
    statement: "The Masters golf tournament is held in Georgia",
    answer: "reyal",
    category: "sports",
    difficulty: "medium",
  },
  {
    id: "spo_medium_16",
    statement: "Formula 1 races use oval tracks",
    answer: "faki",
    category: "sports",
    difficulty: "medium",
    explanation:
      "Formula 1 races use road courses and street circuits, not oval tracks!",
  },
  {
    id: "spo_medium_17",
    statement: "The Stanley Cup is awarded in hockey",
    answer: "reyal",
    category: "sports",
    difficulty: "medium",
  },
  {
    id: "spo_medium_18",
    statement: "Beach volleyball teams have 3 players each",
    answer: "faki",
    category: "sports",
    difficulty: "medium",
    explanation: "Beach volleyball teams have 2 players each!",
  },
  {
    id: "spo_medium_19",
    statement: "A regulation soccer goal is 8 yards wide",
    answer: "reyal",
    category: "sports",
    difficulty: "medium",
  },
  {
    id: "spo_medium_20",
    statement: "The Triple Crown in horse racing consists of 4 races",
    answer: "faki",
    category: "sports",
    difficulty: "medium",
    explanation:
      "The Triple Crown consists of 3 races: Kentucky Derby, Preakness Stakes, and Belmont Stakes!",
  },

  // Sports - Hard
  // Sports - Hard (20 questions)
  {
    id: "spo_hard_1",
    statement: "Babe Ruth hit 714 home runs in his career",
    answer: "reyal",
    category: "sports",
    difficulty: "hard",
  },
  {
    id: "spo_hard_2",
    statement: "The first modern Olympics were held in Athens in 1896",
    answer: "reyal",
    category: "sports",
    difficulty: "hard",
  },
  {
    id: "spo_hard_3",
    statement: "Michael Jordan won 7 NBA championships",
    answer: "faki",
    category: "sports",
    difficulty: "hard",
    explanation:
      "Michael Jordan won 6 NBA championships, all with the Chicago Bulls!",
  },
  {
    id: "spo_hard_4",
    statement:
      "The Tour de France cycling race covers approximately 3,500 kilometers",
    answer: "reyal",
    category: "sports",
    difficulty: "hard",
  },
  {
    id: "spo_hard_5",
    statement: "Wayne Gretzky is known as 'The Great One' in hockey",
    answer: "reyal",
    category: "sports",
    difficulty: "hard",
  },
  {
    id: "spo_hard_6",
    statement: "Serena Williams has won 25 Grand Slam singles titles",
    answer: "faki",
    category: "sports",
    difficulty: "hard",
    explanation: "Serena Williams won 23 Grand Slam singles titles!",
  },
  {
    id: "spo_hard_7",
    statement: "The fastest recorded tennis serve is over 160 mph",
    answer: "reyal",
    category: "sports",
    difficulty: "hard",
  },
  {
    id: "spo_hard_8",
    statement: "Muhammad Ali fought in 4 different decades",
    answer: "reyal",
    category: "sports",
    difficulty: "hard",
  },
  {
    id: "spo_hard_9",
    statement: "The Boston Celtics have won 18 NBA championships",
    answer: "faki",
    category: "sports",
    difficulty: "hard",
    explanation: "The Boston Celtics have won 17 NBA championships!",
  },
  {
    id: "spo_hard_10",
    statement: "Pelé scored over 1,000 career goals",
    answer: "reyal",
    category: "sports",
    difficulty: "hard",
  },
  {
    id: "spo_hard_11",
    statement: "The Green Bay Packers have won 4 Super Bowls",
    answer: "faki",
    category: "sports",
    difficulty: "hard",
    explanation:
      "The Green Bay Packers have won 4 NFL championships total, but only 1 Super Bowl (1967)!",
  },
  {
    id: "spo_hard_12",
    statement: "Tiger Woods has won 15 major golf championships",
    answer: "reyal",
    category: "sports",
    difficulty: "hard",
  },
  {
    id: "spo_hard_13",
    statement: "The longest tennis match in history lasted over 11 hours",
    answer: "reyal",
    category: "sports",
    difficulty: "hard",
  },
  {
    id: "spo_hard_14",
    statement: "Kareem Abdul-Jabbar scored 38,387 career NBA points",
    answer: "reyal",
    category: "sports",
    difficulty: "hard",
  },
  {
    id: "spo_hard_15",
    statement: "The New York Yankees have won 28 World Series titles",
    answer: "faki",
    category: "sports",
    difficulty: "hard",
    explanation: "The New York Yankees have won 27 World Series titles!",
  },
  {
    id: "spo_hard_16",
    statement: "Usain Bolt's 100m world record is 9.58 seconds",
    answer: "reyal",
    category: "sports",
    difficulty: "hard",
  },
  {
    id: "spo_hard_17",
    statement: "The Indianapolis 500 race is 400 laps long",
    answer: "faki",
    category: "sports",
    difficulty: "hard",
    explanation: "The Indianapolis 500 is 200 laps long, covering 500 miles!",
  },
  {
    id: "spo_hard_18",
    statement: "Wilt Chamberlain once scored 100 points in a single NBA game",
    answer: "reyal",
    category: "sports",
    difficulty: "hard",
  },
  {
    id: "spo_hard_19",
    statement: "The Ryder Cup in golf is held every 3 years",
    answer: "faki",
    category: "sports",
    difficulty: "hard",
    explanation: "The Ryder Cup is held every 2 years!",
  },
  {
    id: "spo_hard_20",
    statement: "Jesse Owens won 4 gold medals at the 1936 Berlin Olympics",
    answer: "reyal",
    category: "sports",
    difficulty: "hard",
  },
  // Sports - Expert
  // Sports - Expert (20 questions)
  {
    id: "spo_expert_1",
    statement: "Don Bradman's career Test batting average was 99.94",
    answer: "reyal",
    category: "sports",
    difficulty: "expert",
  },
  {
    id: "spo_expert_2",
    statement: "The original Olympic marathon distance was exactly 26 miles",
    answer: "faki",
    category: "sports",
    difficulty: "expert",
    explanation:
      "The original marathon was about 24-25 miles. The 26.2 mile distance was set for the 1908 London Olympics!",
  },
  {
    id: "spo_expert_3",
    statement: "Cy Young won 511 career games in Major League Baseball",
    answer: "reyal",
    category: "sports",
    difficulty: "expert",
  },
  {
    id: "spo_expert_4",
    statement: "The Miracle on Ice occurred in the 1976 Winter Olympics",
    answer: "faki",
    category: "sports",
    difficulty: "expert",
    explanation:
      "The Miracle on Ice occurred at the 1980 Winter Olympics in Lake Placid!",
  },
  {
    id: "spo_expert_5",
    statement:
      "Secretariat won the Triple Crown in 1973 by a combined margin of 32 lengths",
    answer: "faki",
    category: "sports",
    difficulty: "expert",
    explanation:
      "Secretariat won by a combined margin of 33 lengths (2.5 + 2.5 + 31 at Belmont)!",
  },
  {
    id: "spo_expert_6",
    statement: "The first FIFA World Cup had 13 teams participate",
    answer: "reyal",
    category: "sports",
    difficulty: "expert",
  },
  {
    id: "spo_expert_7",
    statement:
      "Wilt Chamberlain averaged 50.4 points per game in the 1961-62 NBA season",
    answer: "reyal",
    category: "sports",
    difficulty: "expert",
  },
  {
    id: "spo_expert_8",
    statement: "The Chicago Bears' 1985 defense allowed 198 total points",
    answer: "faki",
    category: "sports",
    difficulty: "expert",
    explanation:
      "The 1985 Bears defense allowed 198 total points in the regular season plus playoffs combined, but 258 in the regular season alone!",
  },
  {
    id: "spo_expert_9",
    statement: "Joe DiMaggio's hitting streak lasted 56 consecutive games",
    answer: "reyal",
    category: "sports",
    difficulty: "expert",
  },
  {
    id: "spo_expert_10",
    statement:
      "The first Super Bowl was played in 1967 between Green Bay and Kansas City",
    answer: "reyal",
    category: "sports",
    difficulty: "expert",
  },
  {
    id: "spo_expert_11",
    statement: "Gordie Howe played professional hockey in 5 different decades",
    answer: "reyal",
    category: "sports",
    difficulty: "expert",
  },
  {
    id: "spo_expert_12",
    statement: "The Boston Marathon was first run in 1897",
    answer: "faki",
    category: "sports",
    difficulty: "expert",
    explanation:
      "The Boston Marathon was first run in 1897, inspired by the 1896 Olympic marathon!",
  },
  {
    id: "spo_expert_13",
    statement: "UCLA won 88 consecutive basketball games under John Wooden",
    answer: "reyal",
    category: "sports",
    difficulty: "expert",
  },
  {
    id: "spo_expert_14",
    statement:
      "The 'Shot Heard 'Round the World' was hit by Bobby Thomson in 1952",
    answer: "faki",
    category: "sports",
    difficulty: "expert",
    explanation: "Bobby Thomson hit the 'Shot Heard 'Round the World' in 1951!",
  },
  {
    id: "spo_expert_15",
    statement: "Byron Nelson won 18 consecutive PGA Tour events in 1945",
    answer: "faki",
    category: "sports",
    difficulty: "expert",
    explanation: "Byron Nelson won 11 consecutive PGA Tour events in 1945!",
  },
  {
    id: "spo_expert_16",
    statement: "The Edmonton Oilers scored 446 goals in the 1983-84 NHL season",
    answer: "reyal",
    category: "sports",
    difficulty: "expert",
  },
  {
    id: "spo_expert_17",
    statement: "Hank Aaron broke Babe Ruth's home run record on April 8, 1974",
    answer: "reyal",
    category: "sports",
    difficulty: "expert",
  },
  {
    id: "spo_expert_18",
    statement: "The 1980 U.S. Olympic hockey team was coached by Herb Brooks",
    answer: "reyal",
    category: "sports",
    difficulty: "expert",
  },
  {
    id: "spo_expert_19",
    statement: "Red Auerbach won 9 NBA championships as Boston Celtics coach",
    answer: "reyal",
    category: "sports",
    difficulty: "expert",
  },
  {
    id: "spo_expert_20",
    statement:
      "The 1992 Dream Team scored over 120 points in 6 of their 8 Olympic games",
    answer: "faki",
    category: "sports",
    difficulty: "expert",
    explanation:
      "The 1992 Dream Team scored over 100 points in all 8 games, but over 120 points in only 4 games!",
  },
];