import { Question } from "../types";

export const Technology_Questions: Question[] = [
  // Technology - Easy
  {
    id: "tech_easy_1",
    statement: "A smartphone is a type of computer",
    answer: "reyal",
    category: "technology",
    difficulty: "easy",
  },
  {
    id: "tech_easy_2",
    statement: "The logo of Apple is a banana",
    answer: "faki",
    category: "technology",
    difficulty: "easy",
    explanation: "Apple’s logo is an apple with a bite taken out of it.",
  },
  {
    id: "tech_easy_3",
    statement: "Wi-Fi allows devices to connect to the internet wirelessly",
    answer: "reyal",
    category: "technology",
    difficulty: "easy",
  },
  {
    id: "tech_easy_4",
    statement: "Microsoft created the Windows operating system",
    answer: "reyal",
    category: "technology",
    difficulty: "easy",
  },
  {
    id: "tech_easy_5",
    statement: "USB stands for Universal Serial Bus",
    answer: "reyal",
    category: "technology",
    difficulty: "easy",
  },
  {
    id: "tech_easy_6",
    statement: "The PlayStation is made by Nintendo",
    answer: "faki",
    category: "technology",
    difficulty: "easy",
    explanation: "The PlayStation is made by Sony, not Nintendo.",
  },
  {
    id: "tech_easy_7",
    statement: "An email can be sent instantly to another person",
    answer: "reyal",
    category: "technology",
    difficulty: "easy",
  },
  {
    id: "tech_easy_8",
    statement: "HTML is used to design web pages",
    answer: "reyal",
    category: "technology",
    difficulty: "easy",
  },
  {
    id: "tech_easy_9",
    statement:
      "Bluetooth is used for connecting devices wirelessly at short distances",
    answer: "reyal",
    category: "technology",
    difficulty: "easy",
  },
  {
    id: "tech_easy_10",
    statement: "The first name of the company Google was Backrub",
    answer: "reyal",
    category: "technology",
    difficulty: "easy",
  },
  {
    id: "tech_easy_11",
    statement: "A mouse is an input device for a computer",
    answer: "reyal",
    category: "technology",
    difficulty: "easy",
  },
  {
    id: "tech_easy_12",
    statement: "The internet and the World Wide Web are the exact same thing",
    answer: "faki",
    category: "technology",
    difficulty: "easy",
    explanation:
      "The internet is the network of computers, while the Web is a service running on it.",
  },
  {
    id: "tech_easy_13",
    statement: "Bill Gates co-founded Microsoft",
    answer: "reyal",
    category: "technology",
    difficulty: "easy",
  },
  {
    id: "tech_easy_14",
    statement: "You can take a screenshot on a computer",
    answer: "reyal",
    category: "technology",
    difficulty: "easy",
  },
  {
    id: "tech_easy_15",
    statement: "An iPad is a type of tablet",
    answer: "reyal",
    category: "technology",
    difficulty: "easy",
  },
  {
    id: "tech_easy_16",
    statement: "Facebook was created by Elon Musk",
    answer: "faki",
    category: "technology",
    difficulty: "easy",
    explanation: "Facebook was created by Mark Zuckerberg, not Elon Musk.",
  },
  {
    id: "tech_easy_17",
    statement: "PDF stands for Portable Document Format",
    answer: "reyal",
    category: "technology",
    difficulty: "easy",
  },
  {
    id: "tech_easy_18",
    statement: "Ctrl + C is a shortcut for copying text",
    answer: "reyal",
    category: "technology",
    difficulty: "easy",
  },
  {
    id: "tech_easy_19",
    statement: "A virus is a type of software that can harm your computer",
    answer: "reyal",
    category: "technology",
    difficulty: "easy",
  },
  {
    id: "tech_easy_20",
    statement: "The cloud means storing files on your own USB drive",
    answer: "faki",
    category: "technology",
    difficulty: "easy",
    explanation:
      "The cloud means storing files on remote servers accessed via the internet.",
  },
  // Technology - Medium
  {
    id: "tech_med_3",
    statement: "The programming language Python was named after the snake",
    answer: "faki",
    category: "technology",
    difficulty: "medium",
    explanation: "It was named after the British comedy group Monty Python.",
  },
  {
    id: "tech_med_4",
    statement:
      "The logo of Apple originally featured Isaac Newton under an apple tree",
    answer: "reyal",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "tech_med_5",
    statement: "HTML stands for HyperText Markup Language",
    answer: "reyal",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "tech_med_6",
    statement: "The first version of Windows was released in 1985",
    answer: "reyal",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "tech_med_7",
    statement:
      "Moore’s Law predicts that the number of transistors on a chip doubles every two years",
    answer: "reyal",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "tech_med_8",
    statement: "Java and JavaScript are essentially the same language",
    answer: "faki",
    category: "technology",
    difficulty: "medium",
    explanation:
      "Despite the similar names, they are completely different languages.",
  },
  {
    id: "tech_med_9",
    statement: "The first email was sent in the 1970s",
    answer: "reyal",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "tech_med_10",
    statement: "Wi-Fi stands for Wireless Fidelity",
    answer: "faki",
    category: "technology",
    difficulty: "medium",
    explanation: "Wi-Fi doesn’t stand for anything — it’s just a brand name.",
  },
  {
    id: "tech_med_11",
    statement: "Linux was created by Linus Torvalds",
    answer: "reyal",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "tech_med_12",
    statement:
      "Mark Zuckerberg originally created Facebook as a Harvard-only platform",
    answer: "reyal",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "tech_med_13",
    statement: "The programming language C was developed before C++",
    answer: "reyal",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "tech_med_14",
    statement: "Bluetooth technology was named after a Viking king",
    answer: "reyal",
    category: "technology",
    difficulty: "medium",
    explanation:
      "It was named after Harald Bluetooth, a 10th-century Danish king.",
  },
  {
    id: "tech_med_15",
    statement: "PHP originally stood for Personal Home Page",
    answer: "reyal",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "tech_med_16",
    statement: "The video-sharing platform YouTube was launched in 2003",
    answer: "faki",
    category: "technology",
    difficulty: "medium",
    explanation: "YouTube launched in 2005, not 2003.",
  },
  {
    id: "tech_med_17",
    statement: "The first successful graphical web browser was Mosaic",
    answer: "reyal",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "tech_med_18",
    statement:
      "Cloud computing means storing and accessing data over the internet instead of a local computer",
    answer: "reyal",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "tech_med_19",
    statement: "The first Apple Macintosh was released in 1994",
    answer: "faki",
    category: "technology",
    difficulty: "medium",
    explanation: "The first Macintosh was released in 1984, not 1994.",
  },
  {
    id: "tech_med_20",
    statement: "OpenAI, the company behind ChatGPT, was founded in 2015",
    answer: "reyal",
    category: "technology",
    difficulty: "medium",
  },
  // Technology - Hard
  {
    id: "tech_hard_1",
    statement: "Alan Turing is considered the father of computer science",
    answer: "reyal",
    category: "technology",
    difficulty: "hard",
  },
  {
    id: "tech_hard_2",
    statement: "The ENIAC computer used vacuum tubes instead of transistors",
    answer: "reyal",
    category: "technology",
    difficulty: "hard",
  },
  {
    id: "tech_hard_3",
    statement: "COBOL was primarily designed for scientific computing",
    answer: "faki",
    category: "technology",
    difficulty: "hard",
    explanation: "COBOL was designed for business applications, not science.",
  },
  {
    id: "tech_hard_4",
    statement:
      "The programming paradigm of Lisp heavily influenced modern languages like JavaScript",
    answer: "reyal",
    category: "technology",
    difficulty: "hard",
  },
  {
    id: "tech_hard_5",
    statement: "The 'C' programming language was created at Bell Labs",
    answer: "reyal",
    category: "technology",
    difficulty: "hard",
  },
  {
    id: "tech_hard_6",
    statement:
      "Ada Lovelace wrote what is considered the first computer program",
    answer: "reyal",
    category: "technology",
    difficulty: "hard",
  },
  {
    id: "tech_hard_7",
    statement: "The first hard disk drive was introduced by IBM in the 1950s",
    answer: "reyal",
    category: "technology",
    difficulty: "hard",
  },
  {
    id: "tech_hard_8",
    statement:
      "The term ‘debugging’ originated from the removal of a moth in a computer",
    answer: "reyal",
    category: "technology",
    difficulty: "hard",
  },
  {
    id: "tech_hard_9",
    statement: "IPv6 uses 64-bit addresses",
    answer: "faki",
    category: "technology",
    difficulty: "hard",
    explanation: "IPv6 uses 128-bit addresses, not 64-bit.",
  },
  {
    id: "tech_hard_10",
    statement: "Dennis Ritchie was the creator of the Unix operating system",
    answer: "faki",
    category: "technology",
    difficulty: "hard",
    explanation: "Unix was co-created by Ken Thompson and Dennis Ritchie.",
  },
  {
    id: "tech_hard_11",
    statement: "The first website ever created is still online",
    answer: "reyal",
    category: "technology",
    difficulty: "hard",
    explanation: "Tim Berners-Lee’s original CERN site is still accessible.",
  },
  {
    id: "tech_hard_12",
    statement: "A compiler translates source code into machine code directly",
    answer: "reyal",
    category: "technology",
    difficulty: "hard",
  },
  {
    id: "tech_hard_13",
    statement: "The ‘father of the internet’ is Tim Berners-Lee",
    answer: "faki",
    category: "technology",
    difficulty: "hard",
    explanation:
      "Tim Berners-Lee invented the World Wide Web. The ‘fathers of the internet’ are Vint Cerf and Bob Kahn.",
  },
  {
    id: "tech_hard_14",
    statement: "The first microprocessor was Intel 4004",
    answer: "reyal",
    category: "technology",
    difficulty: "hard",
  },
  {
    id: "tech_hard_15",
    statement: "In computer science, Big-O notation describes algorithm speed",
    answer: "reyal",
    category: "technology",
    difficulty: "hard",
  },
  {
    id: "tech_hard_16",
    statement: "The floppy disk was invented after the compact disc (CD)",
    answer: "faki",
    category: "technology",
    difficulty: "hard",
    explanation:
      "Floppy disks came in the 1970s, CDs were developed in the 1980s.",
  },
  {
    id: "tech_hard_17",
    statement: "The first email attachment was sent in 1992",
    answer: "reyal",
    category: "technology",
    difficulty: "hard",
  },
  {
    id: "tech_hard_18",
    statement:
      "Quantum computers use bits that can be 0, 1, or both at the same time",
    answer: "reyal",
    category: "technology",
    difficulty: "hard",
    explanation: "These are called qubits, allowing superposition.",
  },
  {
    id: "tech_hard_19",
    statement: "The Linux mascot Tux is a penguin",
    answer: "reyal",
    category: "technology",
    difficulty: "hard",
  },
  {
    id: "tech_hard_20",
    statement: "Machine learning and AI are exactly the same thing",
    answer: "faki",
    category: "technology",
    difficulty: "hard",
    explanation: "Machine learning is a subset of AI, not the same as AI.",
  },
  // Technology - Expert
  {
    id: "tech_expert_1",
    statement:
      "Moore’s Law predicts that transistor counts on microchips double approximately every 2 years",
    answer: "reyal",
    category: "technology",
    difficulty: "expert",
  },
  {
    id: "tech_expert_2",
    statement: "The first computer virus was called 'ILOVEYOU'",
    answer: "faki",
    category: "technology",
    difficulty: "expert",
    explanation:
      "The first recognized computer virus was 'Creeper' in the 1970s, not 'ILOVEYOU'.",
  },
  {
    id: "tech_expert_3",
    statement: "The Bjarne Stroustrup is known as the creator of C++",
    answer: "reyal",
    category: "technology",
    difficulty: "expert",
  },
  {
    id: "tech_expert_4",
    statement: "TCP/IP became the standard protocol for ARPANET in 1983",
    answer: "reyal",
    category: "technology",
    difficulty: "expert",
  },
  {
    id: "tech_expert_5",
    statement:
      "In blockchain, a hash function is designed to be easily reversible",
    answer: "faki",
    category: "technology",
    difficulty: "expert",
    explanation: "Hash functions are one-way functions, not reversible.",
  },
  {
    id: "tech_expert_6",
    statement: "The term ‘GUI’ was first popularized by Xerox PARC",
    answer: "reyal",
    category: "technology",
    difficulty: "expert",
  },
  {
    id: "tech_expert_7",
    statement: "The UNIX 'fork()' system call creates a new process",
    answer: "reyal",
    category: "technology",
    difficulty: "expert",
  },
  {
    id: "tech_expert_8",
    statement:
      "The concept of public-key cryptography was first published by Whitfield Diffie and Martin Hellman",
    answer: "reyal",
    category: "technology",
    difficulty: "expert",
  },
  {
    id: "tech_expert_9",
    statement:
      "Shor’s algorithm is famous for efficiently factoring large prime numbers",
    answer: "reyal",
    category: "technology",
    difficulty: "expert",
  },
  {
    id: "tech_expert_10",
    statement: "The P vs NP problem has been solved",
    answer: "faki",
    category: "technology",
    difficulty: "expert",
    explanation:
      "The P vs NP problem remains unsolved and is one of the Clay Millennium Prize problems.",
  },
  {
    id: "tech_expert_11",
    statement:
      "Von Neumann architecture describes a system where program instructions and data share the same memory",
    answer: "reyal",
    category: "technology",
    difficulty: "expert",
  },
  {
    id: "tech_expert_12",
    statement:
      "The RSA cryptosystem relies on the difficulty of factoring large integers",
    answer: "reyal",
    category: "technology",
    difficulty: "expert",
  },
  {
    id: "tech_expert_13",
    statement: "The first programming language ever created was Python",
    answer: "faki",
    category: "technology",
    difficulty: "expert",
    explanation:
      "Fortran (1957) and earlier assembly languages predate Python (1991).",
  },
  {
    id: "tech_expert_14",
    statement: "Neural networks were originally inspired by biological neurons",
    answer: "reyal",
    category: "technology",
    difficulty: "expert",
  },
  {
    id: "tech_expert_15",
    statement: "Docker is a type of hypervisor",
    answer: "faki",
    category: "technology",
    difficulty: "expert",
    explanation:
      "Docker uses containerization, not virtualization like a hypervisor.",
  },
  {
    id: "tech_expert_16",
    statement: "The term ‘cloud computing’ originated in the 2000s",
    answer: "reyal",
    category: "technology",
    difficulty: "expert",
  },
  {
    id: "tech_expert_17",
    statement: "DNS stands for Domain Naming Service",
    answer: "faki",
    category: "technology",
    difficulty: "expert",
    explanation: "DNS stands for Domain Name System, not Naming Service.",
  },
  {
    id: "tech_expert_18",
    statement: "Tor was originally developed by the U.S. Navy",
    answer: "reyal",
    category: "technology",
    difficulty: "expert",
  },
  {
    id: "tech_expert_19",
    statement:
      "In relational databases, the ACID properties stand for Atomicity, Consistency, Isolation, and Durability",
    answer: "reyal",
    category: "technology",
    difficulty: "expert",
  },
  {
    id: "tech_expert_20",
    statement:
      "Post-quantum cryptography is designed to be secure against attacks from quantum computers",
    answer: "reyal",
    category: "technology",
    difficulty: "expert",
  },
];